kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  PGADMIN_DEFAULT_EMAIL: 'yuvakiran060@gmail.com'
  PGADMIN_DEFAULT_PASSWORD: 'xFact2005'
  CUSTOM_HEADER: {{ .Values.configmap.data.CUSTOM_HEADER }}
