apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
     
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
       
    spec: # Pod spec
      containers:
      - name: pgadmin4
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        resources:
          requests:
            memory: "300Mi" 
            cpu: "150m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "450Mi"
            cpu: "200m"
