kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  RABBITMQ_ERLANG_COOKIE: 'secret cookie here'
  RABBITMQ_DEFAULT_USER: 'admin'
  RABBITMQ_DEFAULT_PASS: 'demo'
  CUSTOM_HEADER: {{ .Values.configmap.data.CUSTOM_HEADER }}
