kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_USER: 'xfact'
  POSTGRES_PASSWORD: 'xFact2005'
  CUSTOM_HEADER: {{ .Values.configmap.data.CUSTOM_HEADER }}
