apiVersion: v1
kind: Service
metadata:  
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:    
    app: {{ .Values.appName }}
  type: NodePort
  ports:  
  - name: http
    port: 5432
    targetPort: 5432
    nodePort: 30042
